### ISSUE TITLE
Change start system parameters

### ISSUE THREAD

**Issue by citizenveen** [zaesur/fight-night#16]
Start system now starts all voting remotes starting from id 0 up to a certain ID.
Trying to start voting ID 0 gives a bug, 1 should always be the lowest possible number.

Can we get more control over what voting remotes we start? 1-x will maybe not always be possible.
Can we fill in the first and last number, so we can start the system with ID's 100-200 for example?

**Comment by zaesur** [comment]
I will add more fine grained control for the startup of the hardware.

During our last conversation I remember you mentioning that the technician may start and test the hardware a few hours before the start of a show, and some concerns over having the hardware control included in the technician screen.

How would you feel about extracting all of this into a separate page, which is included as a link from the main control screen? That way, the main control screen is not cluttered with these controls.

**Comment by citizenveen** [comment]
It's possible to do it in a separate window, but it's not needed. It's also no problem to leave it at the top of screen, it is however very important that we can control what voting pad ID's we want to startup, not just 1 - x.
I would implement the solution that takes the least amount of time, so the project can be finished as soon as possible.

**Comment by citizenveen** [comment]
In the latest commit, this issue still persists, we can only open the system starting with ID 0 up untill x, issue should still be open I think?

**Comment by zaesur** [comment]
@citizenveen, the issue of voting ids starting at keypad 0 is solved by this commit, hence my closing of the issue. I verified this just now. 6 voters will send 1 up to excluding 7, so 6 remotes. The minimum is set to 1 which will send 1-2 (exclusive).

As for more fine grained control, I will add configuration for the start field later, but more fine grained control than a starting and ending number I can't offer due to the design of the API.
